export const user = {
  login: "jamesgolick",
  id: 37,
  node_id: "MDQ6VXNlcjM3",
  avatar_url: "https://avatars.githubusercontent.com/u/37?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/jamesgolick",
  html_url: "https://github.com/jamesgolick",
  followers_url: "https://api.github.com/users/jamesgolick/followers",
  following_url:
    "https://api.github.com/users/jamesgolick/following{/other_user}",
  gists_url: "https://api.github.com/users/jamesgolick/gists{/gist_id}",
  starred_url:
    "https://api.github.com/users/jamesgolick/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/jamesgolick/subscriptions",
  organizations_url: "https://api.github.com/users/jamesgolick/orgs",
  repos_url: "https://api.github.com/users/jamesgolick/repos",
  events_url: "https://api.github.com/users/jamesgolick/events{/privacy}",
  received_events_url:
    "https://api.github.com/users/jamesgolick/received_events",
  type: "User",
  user_view_type: "public",
  site_admin: false,
  name: "James Golick",
  company: "Normal",
  blog: "http://jamesgolick.com",
  location: "New York",
  email: null,
  hireable: null,
  bio: null,
  twitter_username: null,
  public_repos: 110,
  public_gists: 114,
  followers: 658,
  following: 30,
  created_at: "2008-01-19T22:52:30Z",
  updated_at: "2019-06-05T00:04:42Z",
};
